profile:
  name: asv

validator:
  max_abs_angular_velocity_rad_s: 3.0
  max_abs_linear_acceleration_m_s2: 20.0
  validate_orientation_fields: true
  require_non_zero_timestamp: true
  max_future_timestamp_sec: 0.02
  max_past_age_sec: 0.3
  max_covariance_abs_value: 5000.0
  require_covariance_diagonal_non_negative: true
  require_covariance_symmetric: true
  covariance_symmetry_tolerance: 0.000001
  enable_stationary_drift_check: true
  stationary_accel_magnitude_m_s2: 9.80665
  stationary_accel_tolerance_m_s2: 0.75
  max_stationary_angular_velocity_rad_s: 0.08
  enable_magnetic_anomaly_proxy_check: true
  orientation_covariance_magnetic_anomaly_warn_threshold: 2.5

envelope:
  max_pitch_deg: 20.0
  max_roll_deg: 25.0
  nominal_speed_m_s: 6.0
